name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Build
      run: yarn build

    - name: Deploy to server
      uses: burnett01/rsync-deployments@7.0.1
      with:
        switches: -avzr --delete --no-times --perms --chown=deploy:deploy --chmod=Du=rwx,Dg=rx,Do=r,Fu=rw,Fg=r,Fo=r
        path: dist/
        remote_path: /var/www/${{ secrets.WEBSITE_DOMAIN_NAME }}/
        remote_host: ${{ secrets.SERVER_HOST }}
        remote_user: ${{ secrets.SERVER_USERNAME }}
        remote_key: ${{ secrets.SERVER_SSH_KEY }}