name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Build
      run: yarn build

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          rm -rf /var/www/www.belogia.fr/
          mkdir -p /var/www/www.belogia.fr/
          echo $GITHUB_WORKSPACE
          ls -l $GITHUB_WORKSPACE
          cp -r $GITHUB_WORKSPACE/dist/* /var/www/www.belogia.fr/